---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: solaris10-minimal
    driver:
      provider: virtualbox
      box: tnarik/solaris10-minimal-with-chef
      require_chef_omnibus: 12.0.3
#  - name: ubuntu-12.04
#  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[asset_provider::default]
    attributes:
